import type { Metadata } from 'next'
// eslint-disable-next-line camelcase

import StyledComponentsRegistry from '@/lib/registry'
import { Providers } from './providers'
import { ThemeProvider } from 'styled-components'
import theme from '@/styles/theme'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin']
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin']
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <ThemeProvider theme={theme}>
          <StyledComponentsRegistry>
            <Providers>{children}</Providers>
          </StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  )
}
